# Generated by Django 5.0.2 on 2024-03-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_intenscompra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntensCompra',
            new_name='ItensCompra',
        ),
    ]
